### ISSUE TITLE
Request to Contribute to This Open Source Project

### ISSUE THREAD

**Issue by hackroid** [MGMCN/Team-GYUK#51]
Hello,

I am a 24-year-old Master's student from Japan, and I recently came across your open-source project on GitHub. I am quite interested in the work and would like to contribute a little to the project by learning and collaborating on programming with you.

I have experience in Python backend design and basic knowledge of iOS programming, and I am eager to expand my knowledge by working on this project. I would be grateful if you could consider my request to contribute to part of the project. I look forward to hearing back from you and hope to start learning soon.

Thank you for your time and consideration.

Best regards,
Hackroid

**Comment by MGMCN** [comment]
すみませんが、このリポジトリはプログラミング演習の講義で作っているソフトウェア用なので、受講者以外は入れないのです。
